cmake ../.. \
    -DFREETYPE_INC_SEARCH_PATH=$PWD/../../../freetype/include \
    -DFREETYPE_LIB_SEARCH_PATH=$PWD/../../../freetype/dasbuild/msvc \
    -DFreeImage_INC_SEARCH_PATH=$PWD/../../../freeimage/Source \
    -DFreeImage_LIB_SEARCH_PATH=$PWD/../../../freeimage/dasbuild/msvc \
    -DZLIB_INC_SEARCH_PATH=$PWD/../../../zlib \
    -DZLIB_LIB_SEARCH_PATH=$PWD/../../../zlib/dasbuild/msvc \
    -DZZip_INC_SEARCH_PATH=$PWD/../../../zziplib \
    -DZZip_LIB_SEARCH_PATH=$PWD/../../../zziplib/dasbuild/msvc \
    -DOIS_INC_SEARCH_PATH=$PWD/../../../ois/includes \
    -DOIS_LIB_SEARCH_PATH=$PWD/../../../ois/dasbuild/msvc
